/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MPC
 */
public class KalkuatorStandar extends javax.swing.JFrame {

    /**
     * Creates new form KalkuatorStandar
     */
 String angka = " ";
  double jumlah,angka1,angka2;
    int pilih;

 

    /**
     *
     */
    public KalkuatorStandar() {
        initComponents();
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ang7 = new javax.swing.JButton();
        ang8 = new javax.swing.JButton();
        ang9 = new javax.swing.JButton();
        ang4 = new javax.swing.JButton();
        ang5 = new javax.swing.JButton();
        ang6 = new javax.swing.JButton();
        ang1 = new javax.swing.JButton();
        ang2 = new javax.swing.JButton();
        ang3 = new javax.swing.JButton();
        ang0 = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        total = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        Text1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        akar = new javax.swing.JButton();
        Pangkat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setForeground(new java.awt.Color(0, 255, 102));
        jPanel1.setLayout(null);

        ang7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang7.setText("7");
        ang7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang7ActionPerformed(evt);
            }
        });
        jPanel1.add(ang7);
        ang7.setBounds(70, 220, 50, 40);

        ang8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang8.setText("8");
        ang8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang8ActionPerformed(evt);
            }
        });
        jPanel1.add(ang8);
        ang8.setBounds(160, 220, 50, 40);

        ang9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang9.setText("9");
        ang9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang9ActionPerformed(evt);
            }
        });
        jPanel1.add(ang9);
        ang9.setBounds(250, 220, 50, 40);

        ang4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang4.setText("4");
        ang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang4ActionPerformed(evt);
            }
        });
        jPanel1.add(ang4);
        ang4.setBounds(70, 270, 50, 40);

        ang5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang5.setText("5");
        ang5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang5ActionPerformed(evt);
            }
        });
        jPanel1.add(ang5);
        ang5.setBounds(160, 270, 50, 40);

        ang6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang6.setText("6");
        ang6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang6ActionPerformed(evt);
            }
        });
        jPanel1.add(ang6);
        ang6.setBounds(250, 270, 50, 40);

        ang1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang1.setText("1");
        ang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang1ActionPerformed(evt);
            }
        });
        jPanel1.add(ang1);
        ang1.setBounds(70, 330, 50, 40);

        ang2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang2.setText("2");
        ang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang2ActionPerformed(evt);
            }
        });
        jPanel1.add(ang2);
        ang2.setBounds(160, 330, 50, 40);

        ang3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang3.setText("3");
        ang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang3ActionPerformed(evt);
            }
        });
        jPanel1.add(ang3);
        ang3.setBounds(250, 330, 50, 40);

        ang0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ang0.setText("0");
        ang0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang0ActionPerformed(evt);
            }
        });
        jPanel1.add(ang0);
        ang0.setBounds(160, 390, 50, 40);

        persen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        jPanel1.add(persen);
        persen.setBounds(70, 390, 60, 40);

        koma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        koma.setText(",");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        jPanel1.add(koma);
        koma.setBounds(250, 390, 50, 40);

        kali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kali.setText("X");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali);
        kali.setBounds(330, 220, 50, 40);

        kurang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(330, 270, 50, 40);

        Tambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tambah.setText("+");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        jPanel1.add(Tambah);
        Tambah.setBounds(330, 330, 50, 40);

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total.setText("=");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total);
        total.setBounds(330, 390, 50, 40);

        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(70, 170, 50, 40);

        bagi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi);
        bagi.setBounds(330, 170, 50, 40);

        Text1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(Text1);
        Text1.setBounds(60, 60, 340, 90);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(0, 0, 0));
        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("Kalkulator Standar");
        jPanel1.add(label2);
        label2.setBounds(120, 10, 230, 30);

        akar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        akar.setText("Akar");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });
        jPanel1.add(akar);
        akar.setBounds(230, 170, 80, 40);

        Pangkat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Pangkat.setText("^");
        Pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PangkatActionPerformed(evt);
            }
        });
        jPanel1.add(Pangkat);
        Pangkat.setBounds(147, 170, 60, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ang6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang6ActionPerformed
        // TODO add your handling code here:	
           angka += "6";
           Text1.setText(angka);
    }//GEN-LAST:event_ang6ActionPerformed

    private void ang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang1ActionPerformed
        // TODO add your handling code here:
       angka += "1";
         Text1.setText(angka);
    }//GEN-LAST:event_ang1ActionPerformed

    private void ang5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang5ActionPerformed
        // TODO add your handling code here:
            angka += "5";
           Text1.setText(angka);
    }//GEN-LAST:event_ang5ActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        // TODO add your handling code here:
        angka += ".";
         Text1.setText(angka);
    }//GEN-LAST:event_komaActionPerformed

    private void ang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang3ActionPerformed
        // TODO add your handling code here:
          angka += "3";
          Text1.setText(angka);
    }//GEN-LAST:event_ang3ActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
          Text1.setText("*");
          angka="";
          pilih=3;
    }//GEN-LAST:event_kaliActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
angka1=Double.parseDouble(angka);
Text1.setText("-");
angka="";
pilih=2;
    }//GEN-LAST:event_kurangActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
   Text1.setText("");
angka1=0.0;
angka2=0.0;
jumlah=0.0;
angka="";
        
    }//GEN-LAST:event_clearActionPerformed

    private void ang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
Text1.setText(angka);     
    }//GEN-LAST:event_ang2ActionPerformed

    private void ang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
Text1.setText(angka);
    }//GEN-LAST:event_ang4ActionPerformed

    private void ang7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang7ActionPerformed
        // TODO add your handling code here:
angka += "7";
Text1.setText(angka);
    }//GEN-LAST:event_ang7ActionPerformed

    private void ang8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang8ActionPerformed
        // TODO add your handling code here:
      angka += "8";
Text1.setText(angka);
    }//GEN-LAST:event_ang8ActionPerformed

    private void ang9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
Text1.setText(angka);
    }//GEN-LAST:event_ang9ActionPerformed

    private void ang0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
Text1.setText(angka);
    }//GEN-LAST:event_ang0ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            Text1.setText(angka);
            break;
        case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            Text1.setText(angka);
            break;
        case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            Text1.setText(angka);
            break;
        case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            Text1.setText(angka);
            break;
        case 5:
            jumlah = Math.sqrt(angka1);
            angka = Double.toString(jumlah);
            Text1.setText(angka);
            break;
        case 6:
            jumlah = angka1 / 100;
            angka = Double.toString(jumlah);
            Text1.setText(angka);
            break;
         case 7:
            jumlah = Math.pow(angka1, 2);
            angka = Double.toString(jumlah);
            Text1.setText(angka);
            break;
        case 8:
            jumlah = angka1 % angka2;
            angka = Double.toString(jumlah);
            Text1.setText(angka);
            break;
    }//GEN-LAST:event_totalActionPerformed
    }
    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
       angka1=Double.parseDouble(angka);
       Text1.setText("+");
       angka="";
       pilih=1;
    }//GEN-LAST:event_TambahActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        Text1.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_bagiActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
        Text1.setText("%");
        angka="";
        pilih=6;
    }//GEN-LAST:event_persenActionPerformed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
        Text1.setText("√");
        angka="";
        pilih=5;
    }//GEN-LAST:event_akarActionPerformed

    private void PangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PangkatActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
        Text1.setText("^");
        angka="^";
        pilih=7;
    }//GEN-LAST:event_PangkatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkuatorStandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkuatorStandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkuatorStandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkuatorStandar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkuatorStandar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pangkat;
    private javax.swing.JButton Tambah;
    private java.awt.TextField Text1;
    private javax.swing.JButton akar;
    private javax.swing.JButton ang0;
    private javax.swing.JButton ang1;
    private javax.swing.JButton ang2;
    private javax.swing.JButton ang3;
    private javax.swing.JButton ang4;
    private javax.swing.JButton ang5;
    private javax.swing.JButton ang6;
    private javax.swing.JButton ang7;
    private javax.swing.JButton ang8;
    private javax.swing.JButton ang9;
    private javax.swing.JButton bagi;
    private javax.swing.JButton clear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private java.awt.Label label2;
    private javax.swing.JButton persen;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
