/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanfx;

/**
 *
 * @author MPC
 */
public class pratikum1 extends javax.swing.JFrame {

    /**
     * Creates new form pratikum1
     */
    public pratikum1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        id_tinggi = new javax.swing.JTextField();
        id_berat = new javax.swing.JTextField();
        buttonhitung = new javax.swing.JButton();
        buttonulang = new javax.swing.JButton();
        buttonkeluar = new javax.swing.JButton();
        laki2 = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        id_ideal = new javax.swing.JTextField();
        id_hasil1 = new javax.swing.JTextField();
        id_hasil2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nama");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 60, 50, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tinggi");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 90, 40, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Berat");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 120, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 170, 90, 20);

        nm.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        nm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmActionPerformed(evt);
            }
        });
        jPanel2.add(nm);
        nm.setBounds(110, 50, 200, 30);

        id_tinggi.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        id_tinggi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(id_tinggi);
        id_tinggi.setBounds(110, 83, 70, 30);

        id_berat.setFont(new java.awt.Font("Bodoni MT", 3, 14)); // NOI18N
        id_berat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(id_berat);
        id_berat.setBounds(110, 120, 70, 30);

        buttonhitung.setText("Hitung");
        buttonhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhitungActionPerformed(evt);
            }
        });
        jPanel2.add(buttonhitung);
        buttonhitung.setBounds(33, 210, 90, 30);

        buttonulang.setText("Coba Ulang");
        buttonulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonulangActionPerformed(evt);
            }
        });
        jPanel2.add(buttonulang);
        buttonulang.setBounds(140, 210, 110, 30);

        buttonkeluar.setText("Keluar");
        buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(buttonkeluar);
        buttonkeluar.setBounds(260, 210, 90, 30);

        buttonGroup1.add(laki2);
        laki2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laki2.setText("Laki-Laki");
        laki2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laki2ActionPerformed(evt);
            }
        });
        jPanel2.add(laki2);
        laki2.setBounds(130, 170, 100, 20);

        buttonGroup1.add(perempuan);
        perempuan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        perempuan.setText("Perempuan");
        jPanel2.add(perempuan);
        perempuan.setBounds(250, 170, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Aplikasi cek Ideal");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 10, 230, 40);

        id_ideal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_ideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_idealActionPerformed(evt);
            }
        });
        jPanel2.add(id_ideal);
        id_ideal.setBounds(210, 250, 70, 40);

        id_hasil1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id_hasil1.setText("?");
        jPanel2.add(id_hasil1);
        id_hasil1.setBounds(100, 330, 340, 40);

        id_hasil2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id_hasil2.setText("?");
        id_hasil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_hasil2ActionPerformed(evt);
            }
        });
        jPanel2.add(id_hasil2);
        id_hasil2.setBounds(100, 400, 340, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Berat Badan Ideal Anda");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 260, 170, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Hasil Analisa Kesehatan");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 300, 220, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cm");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(190, 90, 30, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Kg");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(190, 130, 30, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Kg");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(300, 260, 20, 17);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -10, 540, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhitungActionPerformed
        // TODO add your handling code here:
        double t = Double.valueOf(id_tinggi.getText());
        double b = Double.valueOf(id_berat.getText());
        double h = 0;
        String nama = nm.getText();
        
        if(laki2.isSelected()){
            h = (t-100);
        }
        else if(perempuan.isSelected()){
            h = (t-104);
        }
        
        String temp = Double.toString(h);
        
        if(h<b){
            id_ideal.setText(temp);
            id_hasil1.setText("Maaf" +nama+ " Sepertinya anda overweight");
            id_hasil2.setText("Lebih Sering Olahraga");

        }
        else if (h>b){
        id_ideal.setText(temp);
            id_hasil1.setText("Maaf" +nama+ "Sepertinya anda underweight"); 
             id_hasil2.setText("Lebih baik banyak makan makanan yang bergizi"); 
    }
        else {
            id_ideal.setText(temp);
            id_hasil1.setText("Selamat" +nama+ "anda ideal!!!!!!!");  
             id_hasil2.setText("Jagalah kesehatan anda selalu!!!");  
        }
    }//GEN-LAST:event_buttonhitungActionPerformed

    private void buttonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_buttonkeluarActionPerformed

    private void nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmActionPerformed

    private void id_idealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_idealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_idealActionPerformed

    private void laki2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laki2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laki2ActionPerformed

    private void id_hasil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_hasil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_hasil2ActionPerformed

    private void buttonulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonulangActionPerformed
        // TODO add your handling code here:
        nm .setText("");
        id_berat.setText("");
        id_tinggi.setText("");
        id_ideal.setText("");
        id_hasil1.setText("");
        id_hasil2.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_buttonulangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pratikum1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pratikum1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton buttonhitung;
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JButton buttonulang;
    private javax.swing.JTextField id_berat;
    private javax.swing.JTextField id_hasil1;
    private javax.swing.JTextField id_hasil2;
    private javax.swing.JTextField id_ideal;
    private javax.swing.JTextField id_tinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton laki2;
    private javax.swing.JTextField nm;
    private javax.swing.JRadioButton perempuan;
    // End of variables declaration//GEN-END:variables
}
